name: Devnology

on:
  push:
    branches: [ "main", "scraping" ]
  pull_request:
    branches: [ "main", "scraping" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: '127.0.0.1:8000/api/v1/'
    needs: biuld
    steps:
    - name: Run a one-line script
      run: echo Deploy Dev
  
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: '127.0.0.1:8000/api/v1/'
    needs: deploy-dev
    steps:
    - name: Run a one-line script
      run: echo Deploy HMG
  
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: '127.0.0.1:8000/api/v1/'
    needs: deploy-hmg
    steps:
    - name: Run a one-line script
      run: echo Deploy PRD